In [1]:
import numpy as np

Задание 1

Создать массив. Найти среднее по столбцам.

In [10]:
a = np.array([[1, 6],
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [9]:
mean_a = a.mean(axis = 0)
mean_a

array([2. , 8.4])

Задание 2

Получить новый массив вычитанием.

In [12]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Задание 3

Найти скалярое произведение столбцов. Поделить на число наблюдений (строк) минус 1.

In [13]:
c = np.array([a_centered[0, 0], a_centered[1, 0], a_centered[2, 0], a_centered[3, 0], a_centered[4, 0]])
c

array([-1.,  0.,  1.,  1., -1.])

In [14]:
d = np.array([a_centered[0, 1], a_centered[1, 1], a_centered[2, 1], a_centered[3, 1], a_centered[4, 1]])
d

array([-2.4, -0.4,  2.6,  1.6, -1.4])

In [16]:
a_centered_sp = c @ d
a_centered_sp

8.0

In [24]:
n = a.shape[0] - 1
n

4

In [25]:
v = a_centered_sp / n
v


2.0